import { readdirSync } from "fs";
import { join } from "path";
import { AnySelectMenuInteraction, Client, Collection, Events, Interaction } from "discord.js";
import { ISelectMenu } from "../../types/discord_interactions";
import { IEventHandler } from "../../types/event_handler";

function init(client: Client) {

    if (!client.isReady()) return;

    const selectMenus = new Collection<String, ISelectMenu>();
    const commandFiles = readdirSync(join(__dirname, "../../selectmenus")).filter(file => file.endsWith(".js"));

    for (const file of commandFiles) {

        const cmd: ISelectMenu = require(file) as ISelectMenu;
        try {
            console.log(`[Select Menus]: Reading select menu ${cmd.customId}`);
            selectMenus.set(cmd.customId, cmd)
        } catch (error) {
            console.log(`[Select Menus]: Error in file ${file}`);
            continue;
        }
    };

    return selectMenus;
}

const selectMenuEventHandler: IEventHandler = {
    event: Events.InteractionCreate,
    handlerFactory: (client) => {
        const selectMenus = init(client);
        return async (interaction: Interaction) => {
            if (!interaction.isAnySelectMenu()) return
            let cmdInteraction: AnySelectMenuInteraction = interaction;
            let idArgs = cmdInteraction.id.split(':');
            if (!idArgs || idArgs.length === 0) {
                console.error(`[Error]: Select menu idArgs parsing error for ID ${cmdInteraction.id}`);
                return;
            }
            let cmd: ISelectMenu | undefined = selectMenus?.get(idArgs[0]);
            
            if (cmd === undefined) {
                await interaction.reply({content:'Unknown interaction. If a command or component generated by JerryBot generated this response, please report it!'})
                return;
            }
            await cmd.execute(cmdInteraction, []);
        }
    },
}

export default selectMenuEventHandler;