import { readdirSync } from "fs";
import { join } from "path";
import { Collection, Events } from "discord.js";
import { IModal } from "../../adapter_types/discord_interactions";
import { IDiscordClientEventHandler } from "../../adapter_types/bot_client_event_handler";
import { instance as logger } from "../../bot_systems/logger/logger";
import { LogTarget } from "../../adapter_types/logging";

const path = join(__dirname, "../../modals")
const eventHandler: IDiscordClientEventHandler = {

    event: Events.InteractionCreate,
    handlerFactory: (_, __) => {

        const modals = new Collection<String, IModal>();
        const files = (() => {
            try {
                return readdirSync(path).filter(file => file.endsWith(".js"));
            } catch (err) {
                return [];
            }
        }).call(this);
        if (files.length == 0) return async (interaction) => {
            if (!interaction.isModalSubmit()) return;
            await interaction.reply({ content: `Something went wrong, and buttons cannot be handled at the moment. Please report this to a staff member.` });
        }

        for (const file of files) {

            const cmd = require(join(__dirname, `../../modals/${file}`)) as { default: IModal };
            try {
                logger.log(`Reading modal ${cmd.default.customId}`, LogTarget.Info, "Modals");
                modals.set(cmd.default.customId, cmd.default)
            } catch (error) {
                logger.log(`Error in file ${file}`, LogTarget.Error, "Modals");
                continue;
            }
        };
        return async (interaction) => {
            if (!interaction.isModalSubmit()) return
            let idArgs = interaction.customId.split(':');
            if (!idArgs || idArgs.length === 0) {
                logger.log(`Modal idArgs parsing error for ID ${interaction.customId}`, LogTarget.Error, "Modals");
                return;
            }
            let cmd: IModal | undefined = modals?.get(idArgs[0]);

            if (cmd === undefined) {
                await interaction.reply({ content: 'Unknown interaction. If a command or component generated by JerryBot generated this response, please report it!' })
                return;
            }
            await cmd.execute(interaction, idArgs);
        }
    },
    useHandler: true
}

export default eventHandler;